// src/components/cinematic/ScrollCanvas.svelte
<script lang="ts">
  import { onMount, onDestroy } from "svelte";
  import { TOTAL_FRAMES, SECTIONS } from "@/lib/frames";
  import { frames, isInitialLoadComplete, isFallback, updateCurrentFrame, initFrameLoader } from "@/stores/frameLoader";

  // Reactive state — Svelte updates only the DOM nodes that use these
  let showScrollHint = false;
  let introPhase: "none" | "ummah" | "salik" | "done" = "none";
  let introOpacity = 0;
  let showHadith = false;
  let hadithDissolving = false;
  let captionLines = 0;
  let sectionQuote: number | null = null;
  let quoteDissolving = false;
  let baalFadeProgress = 0;
  let progress = 0;

  // Non-reactive engine state — plain variables, no DOM updates
  let canvas: HTMLCanvasElement;
  let ctx: CanvasRenderingContext2D | null = null;
  let dpr = 1;
  let currentFrame = 0;
  let isPlaying = false;
  let currentSectionIdx = 0;
  let atSectionStart = true;
  let scrollCooldown = false;

  function drawFrame(img: HTMLImageElement) {
    if (!canvas || !ctx) return;
    const cw = canvas.width;
    const ch = canvas.height;
    const displayW = cw / dpr;
    const displayH = ch / dpr;
    const imgW = img.naturalWidth;
    const imgH = img.naturalHeight;
    const scale = Math.max(displayW / imgW, displayH / imgH);
    const sw = displayW / scale;
    const sh = displayH / scale;
    const sx = (imgW - sw) * 0.5;
    const sy = (imgH - sh) * 0.5;
    ctx.drawImage(img, sx, sy, sw, sh, 0, 0, cw, ch);
  }

  function drawFrameAtIndex(index: number) {
    let frameImg = frames[index];
    if (!frameImg) {
      for (let i = index - 1; i >= 0; i--) {
        if (frames[i]) { frameImg = frames[i]; break; }
      }
    }
    if (frameImg) drawFrame(frameImg);
  }

  function resizeCanvas() {
    if (!canvas) return;
    dpr = window.devicePixelRatio || 1;
    const w = Math.round(window.innerWidth * dpr);
    const h = Math.round(window.innerHeight * dpr);
    if (canvas.width !== w || canvas.height !== h) {
      canvas.width = w;
      canvas.height = h;
      ctx = canvas.getContext("2d", { alpha: false });
    }
    drawFrameAtIndex(currentFrame);
  }

  // Drive overlay state based on frame position — called every frame during playback
  function updateOverlayState(sectionIndex: number, frameIdx: number) {
    // Section 0: intro logos + captions
    if (sectionIndex === 0) {
      const f = frameIdx;
      if (f < 10) { introPhase = "ummah"; introOpacity = f / 10; }
      else if (f < 50) { introPhase = "ummah"; introOpacity = 1; }
      else if (f < 65) { introPhase = "ummah"; introOpacity = 1 - (f - 50) / 15; }
      else if (f < 75) { introPhase = "salik"; introOpacity = (f - 65) / 10; }
      else if (f < 130) { introPhase = "salik"; introOpacity = 1; }
      else if (f < 145) { introPhase = "salik"; introOpacity = 1 - (f - 130) / 15; }
      else { introPhase = "done"; introOpacity = 0; }

      if (f < 165) { captionLines = 0; showHadith = false; }
      else if (f < 190) { captionLines = 1; showHadith = true; hadithDissolving = false; }
      else if (f < 215) { captionLines = 2; showHadith = true; hadithDissolving = false; }
      else { captionLines = 3; showHadith = true; hadithDissolving = false; }
    }

    // Section quotes
    const quoteConfig: Record<number, { base: number; threshold: number }> = {
      1: { base: 241, threshold: 136 },
      2: { base: 392, threshold: 136 },
      3: { base: 543, threshold: 101 },
      4: { base: 664, threshold: 101 },
    };

    const cfg = quoteConfig[sectionIndex];
    if (cfg) {
      const rel = frameIdx - cfg.base;
      if (rel < cfg.threshold) {
        sectionQuote = null;
        baalFadeProgress = 0;
      } else {
        sectionQuote = sectionIndex;
        quoteDissolving = false;
        baalFadeProgress = Math.min(1, (rel - cfg.threshold) / 15);
      }
    } else if (sectionIndex !== 0 && sectionQuote !== null) {
      sectionQuote = null;
      quoteDissolving = false;
    }
  }

  function playSection(sectionIndex: number, reverse = false): Promise<void> {
    return new Promise((resolve) => {
      if (sectionIndex < 0 || sectionIndex >= SECTIONS.length) { resolve(); return; }
      if (isPlaying) { resolve(); return; }

      isPlaying = true;
      showScrollHint = false;

      // Dissolve quotes when scrolling forward
      if (sectionQuote !== null && !reverse) {
        quoteDissolving = true;
        setTimeout(() => { sectionQuote = null; quoteDissolving = false; }, 1500);
      }
      // Dissolve captions when leaving section 0 forward
      if (showHadith && sectionIndex > 0 && !reverse) {
        hadithDissolving = true;
        setTimeout(() => { showHadith = false; hadithDissolving = false; captionLines = 0; }, 1500);
      }
      // Reversing into section 0
      if (sectionIndex === 0 && reverse) {
        hadithDissolving = false;
        showHadith = true;
        captionLines = 3;
      }

      const section = SECTIONS[sectionIndex];
      const startFrame = section.startFrame - 1;
      const endFrame = section.endFrame - 1;
      let frameIdx = reverse ? endFrame : startFrame;
      const FPS_INTERVAL = 1000 / 48;
      let lastTime = performance.now();

      // Preload
      for (let i = startFrame; i <= endFrame; i++) { updateCurrentFrame(i); }

      const playNext = (now: number) => {
        const done = reverse ? frameIdx < startFrame : frameIdx > endFrame;
        if (done) {
          isPlaying = false;

          if (reverse && sectionIndex > 0) {
            const prevSection = sectionIndex - 1;
            const prevEndFrame = SECTIONS[prevSection].endFrame - 1;
            currentFrame = prevEndFrame;
            drawFrameAtIndex(prevEndFrame);
            currentSectionIdx = prevSection;
            atSectionStart = false;
            if (prevSection > 0) {
              sectionQuote = prevSection;
              quoteDissolving = false;
            } else if (prevSection === 0) {
              showHadith = true; captionLines = 3; hadithDissolving = false;
            }
          } else {
            currentSectionIdx = sectionIndex;
            atSectionStart = reverse;
          }

          progress = reverse
            ? (sectionIndex > 0 ? SECTIONS[sectionIndex - 1].endFrame / TOTAL_FRAMES : (section.startFrame - 1) / TOTAL_FRAMES)
            : section.endFrame / TOTAL_FRAMES;

          if (sectionIndex === 0) {
            if (reverse) {
              introPhase = "ummah"; introOpacity = 0;
              showHadith = false; captionLines = 0;
            } else {
              introPhase = "done"; introOpacity = 0;
              showHadith = true; captionLines = 3;
            }
          }

          if (!(sectionIndex === 0 && reverse)) {
            showScrollHint = true;
            if (!reverse && sectionIndex > 0) {
              sectionQuote = sectionIndex;
              quoteDissolving = false;
            }
          }

          resolve();
          return;
        }

        const elapsed = now - lastTime;
        if (elapsed >= FPS_INTERVAL) {
          lastTime = now - (elapsed % FPS_INTERVAL);
          currentFrame = frameIdx;
          drawFrameAtIndex(frameIdx);

          // Update overlay state every frame — Svelte only updates changed DOM nodes
          updateOverlayState(sectionIndex, frameIdx);
          progress = frameIdx / TOTAL_FRAMES;

          if (reverse) { frameIdx--; } else { frameIdx++; }
        }
        requestAnimationFrame(playNext);
      };
      requestAnimationFrame(playNext);
    });
  }

  function handleScroll(forward: boolean) {
    if (isPlaying || scrollCooldown) return;
    if (forward) {
      const target = atSectionStart ? currentSectionIdx : currentSectionIdx + 1;
      if (target < SECTIONS.length) {
        scrollCooldown = true;
        playSection(target);
        setTimeout(() => { scrollCooldown = false; }, 150);
      }
    } else {
      const target = atSectionStart ? currentSectionIdx - 1 : currentSectionIdx;
      if (target >= 0) {
        scrollCooldown = true;
        playSection(target, true);
        setTimeout(() => { scrollCooldown = false; }, 150);
      }
    }
  }

  let touchStartY = 0;

  function onWheel(e: WheelEvent) {
    e.preventDefault();
    const delta = Math.abs(e.deltaY) > Math.abs(e.deltaX) ? e.deltaY : e.deltaX;
    if (delta > 10) handleScroll(true);
    else if (delta < -10) handleScroll(false);
  }

  function onTouchStart(e: TouchEvent) { touchStartY = e.touches[0].clientY; }

  function onTouchEnd(e: TouchEvent) {
    const diffY = touchStartY - e.changedTouches[0].clientY;
    if (Math.abs(diffY) > 50) handleScroll(diffY > 0);
  }

  function onKeydown(e: KeyboardEvent) {
    if (isPlaying) return;
    if (e.key === "ArrowRight" || e.key === "ArrowDown") handleScroll(true);
    else if (e.key === "ArrowLeft" || e.key === "ArrowUp") handleScroll(false);
  }

  onMount(() => {
    initFrameLoader();

    // Wait for initial load
    const unsub = isInitialLoadComplete.subscribe((loaded) => {
      if (loaded) {
        resizeCanvas();
        drawFrameAtIndex(0);
        setTimeout(() => playSection(0), 500);
        unsub();
      }
    });

    window.addEventListener("resize", resizeCanvas);
    document.body.style.overflow = "hidden";

    return () => {
      window.removeEventListener("resize", resizeCanvas);
      document.body.style.overflow = "";
    };
  });
</script>

<svelte:window
  on:wheel|preventDefault={onWheel}
  on:touchstart={onTouchStart}
  on:touchend={onTouchEnd}
  on:keydown={onKeydown}
/>

{#if !$isInitialLoadComplete}
  <!-- Loading screen -->
  <div class="fixed inset-0 z-50 flex items-center justify-center bg-black">
    <div class="text-center text-white">
      <img src="/salik-foundation-logo.png" alt="Salik Foundation" class="mx-auto mb-6 h-12 opacity-60" />
      <div class="mb-4 text-sm tracking-[0.2em] uppercase text-white/50">Loading experience...</div>
      <div class="mx-auto h-1 w-48 overflow-hidden rounded-full bg-white/20">
        <div class="h-full rounded-full bg-[#4AB3E2]" style="width: 50%"></div>
      </div>
    </div>
  </div>
{:else}
  <div class="fixed inset-0" style="contain: layout style paint">
    <canvas
      bind:this={canvas}
      class="fixed left-0 top-0 w-screen h-screen"
      style="z-index: 2; will-change: contents;"
    ></canvas>

    <!-- Cinematic intro overlays -->
    {#if introPhase !== "none" && introPhase !== "done"}
      <div
        class="fixed inset-0 flex items-start justify-center pointer-events-none"
        style="z-index: 8; opacity: {introOpacity}; padding-top: 8vh;"
      >
        {#if introPhase === "ummah"}
          <div class="flex flex-col items-center gap-4">
            <p class="text-base md:text-lg tracking-[0.4em] uppercase" style="color: #ffffff; font-family: 'Montserrat', sans-serif; font-weight: 300; text-shadow: 0 2px 20px rgba(0,0,0,0.8), 0 0 40px rgba(0,0,0,0.5); letter-spacing: 0.4em;">
              Produced by
            </p>
            <img src="/ummah-media-logo.png" alt="Ummah Media Corporation" class="h-36 md:h-48" style="filter: drop-shadow(0 4px 30px rgba(0,0,0,0.8));" />
          </div>
        {/if}
        {#if introPhase === "salik"}
          <div class="flex flex-col items-center">
            <img src="/salik-foundation-full-logo.png" alt="Salik Foundation" class="h-40 md:h-56" style="filter: drop-shadow(0 4px 30px rgba(0,0,0,0.8));" />
          </div>
        {/if}
      </div>
    {/if}

    <!-- Section 0: 500 YEARS OF DARKNESS -->
    {#if showHadith}
      <div
        class="fixed inset-0 flex items-center justify-center pointer-events-none"
        class:caption-dissolve={hadithDissolving}
        style="z-index: 9;"
      >
        <div class="text-center px-8 max-w-4xl flex flex-col items-center gap-2">
          <h2 style="color: #FFFFFF; font-family: 'Bebas Neue', sans-serif; font-weight: 400; font-size: clamp(3rem, 10vw, 8rem); line-height: 0.95; letter-spacing: 0.04em; text-shadow: 0 0 40px rgba(0,0,0,0.9), 0 0 80px rgba(0,0,0,0.7), 0 4px 12px rgba(0,0,0,0.9); opacity: {captionLines >= 1 ? 1 : 0}; transform: translateY({captionLines >= 1 ? 0 : 20}px); transition: opacity 0.8s ease-out, transform 0.8s ease-out; margin: 0;">
            500 Years
          </h2>
          <h2 style="color: #FFFFFF; font-family: 'Bebas Neue', sans-serif; font-weight: 400; font-size: clamp(3rem, 10vw, 8rem); line-height: 0.95; letter-spacing: 0.04em; text-shadow: 0 0 40px rgba(0,0,0,0.9), 0 0 80px rgba(0,0,0,0.7), 0 4px 12px rgba(0,0,0,0.9); opacity: {captionLines >= 2 ? 1 : 0}; transform: translateY({captionLines >= 2 ? 0 : 20}px); transition: opacity 0.8s ease-out, transform 0.8s ease-out; margin: 0;">
            Of Darkness
          </h2>
          <p class="mt-4" style="color: #F0D878; font-family: Georgia, serif; font-style: italic; font-size: clamp(1rem, 2.5vw, 1.5rem); text-shadow: 0 0 30px rgba(0,0,0,0.9), 0 0 60px rgba(0,0,0,0.7), 0 4px 8px rgba(0,0,0,0.9); opacity: {captionLines >= 3 ? 1 : 0}; transform: translateY({captionLines >= 3 ? 0 : 15}px); transition: opacity 1.2s ease-out, transform 1.2s ease-out; letter-spacing: 0.15em;">
            No law. No scripture. No guidance.
          </p>
        </div>
      </div>
    {/if}

    <!-- Section quotes -->
    {#if sectionQuote !== null}
      <div class="fixed inset-0 pointer-events-none" class:caption-dissolve={quoteDissolving} style="z-index: 9;">

        {#if sectionQuote === 1}
          <div class="absolute top-0" style="left: 25vw; padding-top: 8vh; max-width: 650px; opacity: {quoteDissolving ? 1 : baalFadeProgress}; transform: translateY({quoteDissolving ? 0 : (1 - baalFadeProgress) * 15}px);">
            <h2 style="color: #FFFFFF; font-family: 'Bebas Neue', sans-serif; font-size: clamp(2.5rem, 7vw, 5.5rem); line-height: 0.95; letter-spacing: 0.04em; text-align: left; text-shadow: 0 0 40px rgba(0,0,0,0.9), 0 0 80px rgba(0,0,0,0.7), 0 4px 12px rgba(0,0,0,0.9); margin: 0;">
              They Bowed<br/>To Stone
            </h2>
            <p class="mt-4" style="color: #F0D878; font-family: Georgia, serif; font-style: italic; font-size: clamp(0.9rem, 2vw, 1.3rem); text-align: left; text-shadow: 0 0 30px rgba(0,0,0,0.9), 0 0 60px rgba(0,0,0,0.7), 0 4px 8px rgba(0,0,0,0.9); line-height: 1.5;">
              &ldquo;Do you call upon Baal and abandon the Best of Creators &mdash;<br/>Allah, your Lord and the Lord of your forefathers?&rdquo;
            </p>
            <p class="mt-2 text-xs md:text-sm tracking-[0.2em] uppercase" style="color: rgba(240,216,120,0.4); font-family: 'Montserrat', sans-serif; font-weight: 300; text-align: left; text-shadow: 0 2px 20px rgba(0,0,0,0.9);">
              Qur&rsquo;an 37:125-126
            </p>
          </div>
        {/if}

        {#if sectionQuote === 2}
          <div class="flex flex-col items-center pt-[2vh]" style="opacity: {quoteDissolving ? 1 : baalFadeProgress}; transform: translateY({quoteDissolving ? 0 : (1 - baalFadeProgress) * 20}px);">
            <img src="/quran-open.webp" alt="The Holy Qur'an" class="h-48 md:h-64 lg:h-80 mb-6" style="filter: drop-shadow(0 0 40px rgba(200,168,78,0.4)) drop-shadow(0 4px 20px rgba(0,0,0,0.8));" />
            <h2 style="color: #FFFFFF; font-family: 'Bebas Neue', sans-serif; font-size: clamp(2.5rem, 8vw, 6rem); line-height: 0.95; letter-spacing: 0.04em; text-shadow: 0 0 40px rgba(0,0,0,0.9), 0 0 80px rgba(0,0,0,0.7), 0 4px 12px rgba(0,0,0,0.9); margin: 0; text-align: center;">
              Allah&rsquo;s Mercy<br/>Sent Light
            </h2>
            <p class="mt-4" style="color: #F0D878; font-family: Georgia, serif; font-style: italic; font-size: clamp(0.9rem, 2vw, 1.3rem); text-shadow: 0 0 30px rgba(0,0,0,0.9), 0 0 60px rgba(0,0,0,0.7), 0 4px 8px rgba(0,0,0,0.9); line-height: 1.7; text-align: center; max-width: 600px; padding: 0 2rem;">
              &ldquo;A Book sent down to bring mankind<br/>out of darkness and into light.&rdquo;
            </p>
            <p class="mt-2 text-xs md:text-sm tracking-[0.3em] uppercase" style="color: rgba(240,216,120,0.4); font-family: 'Montserrat', sans-serif; font-weight: 300; text-shadow: 0 2px 20px rgba(0,0,0,0.9);">
              Qur&rsquo;an 14:1
            </p>
          </div>
        {/if}

        {#if sectionQuote === 3}
          <div class="flex flex-col items-center justify-center" style="height: 100vh; opacity: {quoteDissolving ? 1 : baalFadeProgress}; transform: translateY({quoteDissolving ? 0 : (1 - baalFadeProgress) * 20}px);">
            <h2 style="color: #FFFFFF; font-family: 'Bebas Neue', sans-serif; font-size: clamp(3.5rem, 12vw, 9rem); line-height: 0.95; letter-spacing: 0.04em; text-shadow: 0 0 50px rgba(0,0,0,0.9), 0 0 100px rgba(0,0,0,0.7), 0 4px 12px rgba(0,0,0,0.9); margin: 0; text-align: center;">
              Everything<br/>Changed
            </h2>
            <p class="mt-4" style="color: #F0D878; font-family: Georgia, serif; font-style: italic; font-size: clamp(1rem, 2.5vw, 1.5rem); text-shadow: 0 0 30px rgba(0,0,0,0.9), 0 0 60px rgba(0,0,0,0.7), 0 4px 8px rgba(0,0,0,0.9); text-align: center; letter-spacing: 0.1em;">
              One revelation. One message. One God.
            </p>
          </div>
        {/if}

        {#if sectionQuote === 4}
          <div class="flex flex-col items-center justify-center" style="height: 100vh; opacity: {quoteDissolving ? 1 : baalFadeProgress}; transform: translateY({quoteDissolving ? 0 : (1 - baalFadeProgress) * 20}px);">
            <h2 style="color: #FFFFFF; font-family: 'Bebas Neue', sans-serif; font-size: clamp(3rem, 10vw, 8rem); line-height: 0.95; letter-spacing: 0.04em; text-shadow: 0 0 50px rgba(0,0,0,0.9), 0 0 100px rgba(0,0,0,0.7), 0 4px 12px rgba(0,0,0,0.9); margin: 0; text-align: center;">
              The World<br/>Listened
            </h2>
            <p class="mt-4" style="color: #F0D878; font-family: Georgia, serif; font-style: italic; font-size: clamp(1rem, 2.5vw, 1.5rem); text-shadow: 0 0 30px rgba(0,0,0,0.9), 0 0 60px rgba(0,0,0,0.7), 0 4px 8px rgba(0,0,0,0.9); text-align: center; letter-spacing: 0.08em; max-width: 600px; padding: 0 2rem;">
              The message crossed every ocean, every mountain, every border.
            </p>
          </div>
        {/if}
      </div>
    {/if}

    <!-- Scroll HUD -->
    <div class="fixed bottom-12 left-0 right-0 flex justify-center pointer-events-none" style="z-index: 10; opacity: {showScrollHint ? 1 : 0}; transition: opacity 1.5s ease;">
      <div class="flex flex-col items-center select-none" style="animation: cutsceneFloat 3s ease-in-out infinite;">
        <div class="flex items-center gap-5 mb-4">
          <div style="width: 120px; height: 2px; background: linear-gradient(to right, transparent, #E8D080); box-shadow: 0 0 12px rgba(232,208,128,0.6); animation: lineGlow 2.5s ease-in-out infinite;"></div>
          <span class="text-3xl md:text-4xl tracking-[0.5em] uppercase" style="color: #F0D878; font-family: 'Montserrat', sans-serif; font-weight: 700; text-shadow: 0 0 25px rgba(240,216,120,0.9), 0 0 50px rgba(240,216,120,0.5), 0 0 80px rgba(200,168,78,0.3), 0 2px 6px rgba(0,0,0,0.9); animation: textGlow 2.5s ease-in-out infinite;">
            Scroll
          </span>
          <div style="width: 120px; height: 2px; background: linear-gradient(to left, transparent, #E8D080); box-shadow: 0 0 12px rgba(232,208,128,0.6); animation: lineGlow 2.5s ease-in-out infinite;"></div>
        </div>
        <div class="flex flex-col items-center" style="gap: 3px;">
          <svg width="40" height="20" viewBox="0 0 40 20" fill="none" style="animation: chevronCascade 1.8s ease-in-out infinite; filter: drop-shadow(0 0 12px rgba(240,216,120,0.8));">
            <path d="M6 4L20 16L34 4" stroke="#F0D878" stroke-width="3" stroke-linecap="round" stroke-linejoin="round" />
          </svg>
          <svg width="40" height="20" viewBox="0 0 40 20" fill="none" style="animation: chevronCascade 1.8s ease-in-out 0.2s infinite; filter: drop-shadow(0 0 12px rgba(240,216,120,0.6));">
            <path d="M6 4L20 16L34 4" stroke="#F0D878" stroke-width="3" stroke-linecap="round" stroke-linejoin="round" />
          </svg>
          <svg width="40" height="20" viewBox="0 0 40 20" fill="none" style="animation: chevronCascade 1.8s ease-in-out 0.4s infinite; filter: drop-shadow(0 0 12px rgba(240,216,120,0.4));">
            <path d="M6 4L20 16L34 4" stroke="#F0D878" stroke-width="3" stroke-linecap="round" stroke-linejoin="round" />
          </svg>
        </div>
      </div>
    </div>

    <!-- Progress bar -->
    {#if progress > 0.05 && progress < 0.9}
      <div class="fixed bottom-0 left-0 right-0 z-20 h-[2px]" style="opacity: {progress < 0.1 ? (progress - 0.05) / 0.05 : progress > 0.85 ? (0.9 - progress) / 0.05 : 1}; will-change: opacity;">
        <div class="h-full bg-white/40" style="width: {progress * 100}%; will-change: width; transition: width 80ms linear;"></div>
      </div>
    {/if}
  </div>
{/if}

<style>
  @keyframes cutsceneFloat {
    0%, 100% { transform: translateY(0); }
    50% { transform: translateY(-5px); }
  }
  @keyframes chevronCascade {
    0% { opacity: 0.1; transform: translateY(-4px); }
    40% { opacity: 1; transform: translateY(0); }
    70% { opacity: 0.5; transform: translateY(4px); }
    100% { opacity: 0.1; transform: translateY(6px); }
  }
  @keyframes textGlow {
    0%, 100% { opacity: 0.85; }
    50% { opacity: 1; }
  }
  @keyframes lineGlow {
    0%, 100% { opacity: 0.6; }
    50% { opacity: 1; }
  }
  @keyframes captionDissolveOut {
    0% { opacity: 1; transform: translateY(0); filter: blur(0px); }
    100% { opacity: 0; transform: translateY(-30px); filter: blur(4px); }
  }
  :global(.caption-dissolve p:nth-child(1)) { animation: captionDissolveOut 1.2s ease-in forwards; }
  :global(.caption-dissolve p:nth-child(2)) { animation: captionDissolveOut 1.2s ease-in 0.15s forwards; }
  :global(.caption-dissolve p:nth-child(3)) { animation: captionDissolveOut 1.2s ease-in 0.3s forwards; }
  :global(.caption-dissolve h2:nth-child(1)) { animation: captionDissolveOut 1.2s ease-in forwards; }
  :global(.caption-dissolve h2:nth-child(2)) { animation: captionDissolveOut 1.2s ease-in 0.15s forwards; }
</style>

// src/components/cinematic/ScrollCanvas.tsx
import { useRef, useEffect, useImperativeHandle, forwardRef, useCallback, useState } from "react";
import { useFrameLoader } from "@/hooks/useFrameLoader";
import { TOTAL_FRAMES, INITIAL_BATCH_SIZE, FLASH_FRAME_COUNT, SECTIONS, TARGET_FPS, getFocalPointForFrame, DEFAULT_FOCAL_POINT } from "@/lib/frames";
import type { FocalPoint } from "@/lib/frames";
import IntroOverlay from "./overlays/IntroOverlay";
import Section0Caption from "./overlays/Section0Caption";
import SectionQuotes from "./overlays/SectionQuotes";
import ScrollHint from "./overlays/ScrollHint";

export interface ScrollCanvasHandle {
  playFlashSequence: () => Promise<void>;
}

interface ScrollCanvasProps {
  onProgressChange?: (progress: number) => void;
  onFallback?: () => void;
}

const ScrollCanvas = forwardRef<ScrollCanvasHandle, ScrollCanvasProps>(
  function ScrollCanvas({ onProgressChange, onFallback }, ref) {
    const canvasRef = useRef<HTMLCanvasElement>(null);
    const ctxRef = useRef<CanvasRenderingContext2D | null>(null);
    const currentFrameRef = useRef(0);
    const isFlashingRef = useRef(false);
    const isPlayingRef = useRef(false);
    const currentSectionRef = useRef(0);
    const [currentSection, setCurrentSection] = useState(0);
    const atSectionStartRef = useRef(true); // true = at start of section, false = at end
    const [showScrollHint, setShowScrollHint] = useState(false);
    const [introPhase, setIntroPhase] = useState<"none" | "ummah" | "salik" | "done">("none");
    const introOpacityRef = useRef(0);
    const introOverlayElRef = useRef<HTMLDivElement>(null);
    const [showHadith, setShowHadith] = useState(false);
    const [hadithDissolving, setHadithDissolving] = useState(false);
    const [captionLines, setCaptionLines] = useState<number>(0); // 0-3 lines visible
    const showHadithRef = useRef(false);
    const [sectionQuote, setSectionQuote] = useState<number | null>(null);
    const [quoteDissolving, setQuoteDissolving] = useState(false);
    const sectionQuoteRef = useRef<number | null>(null);
    const baalFadeRef = useRef(0);
    const quoteInnerElRef = useRef<HTMLDivElement>(null);
    const quoteDisolvingRef = useRef(false);
    const scrollCooldownRef = useRef(false);
    const idleLoopRef = useRef<number | null>(null);

    const { frames, flashFrames, isInitialLoadComplete, isFallback, updateCurrentFrame } =
      useFrameLoader();

    useEffect(() => {
      if (isFallback && onFallback) onFallback();
    }, [isFallback, onFallback]);

    // Draw a frame to the canvas with cover crop behavior (Retina-aware)
    // Focal point shifts the crop origin so the subject stays visible on mobile
    const drawFrame = useCallback((img: HTMLImageElement, focal: FocalPoint = DEFAULT_FOCAL_POINT) => {
      const canvas = canvasRef.current;
      if (!canvas) return;
      if (!ctxRef.current) ctxRef.current = canvas.getContext("2d");
      const ctx = ctxRef.current;
      if (!ctx) return;

      const dpr = window.devicePixelRatio || 1;
      const displayW = canvas.width / dpr;
      const displayH = canvas.height / dpr;
      const imgW = img.naturalWidth;
      const imgH = img.naturalHeight;

      const scale = Math.max(displayW / imgW, displayH / imgH);
      const sw = displayW / scale;
      const sh = displayH / scale;
      // Anchor crop to focal point, clamped so we never read outside the image
      const sx = Math.max(0, Math.min(imgW - sw, focal.x * imgW - sw / 2));
      const sy = Math.max(0, Math.min(imgH - sh, focal.y * imgH - sh / 2));

      ctx.drawImage(img, sx, sy, sw, sh, 0, 0, canvas.width, canvas.height);
    }, []);

    // Draw frame at given index (hold last loaded if target isn't ready)
    const drawFrameAtIndex = useCallback(
      (index: number) => {
        let frameImg = frames.current[index];
        if (!frameImg) {
          for (let i = index - 1; i >= 0; i--) {
            if (frames.current[i]) {
              frameImg = frames.current[i];
              break;
            }
          }
        }
        if (frameImg) drawFrame(frameImg, getFocalPointForFrame(index));
      },
      [frames, drawFrame]
    );

    // Resize canvas to match viewport
    const resizeCanvas = useCallback(() => {
      const canvas = canvasRef.current;
      if (!canvas) return;
      const dpr = window.devicePixelRatio || 1;
      const w = Math.round(window.innerWidth * dpr);
      const h = Math.round(window.innerHeight * dpr);
      if (canvas.width !== w || canvas.height !== h) {
        canvas.width = w;
        canvas.height = h;
      }
      const idx = currentFrameRef.current;
      let frameImg = frames.current[idx];
      if (!frameImg) {
        for (let i = idx - 1; i >= 0; i--) {
          if (frames.current[i]) { frameImg = frames.current[i]; break; }
        }
      }
      if (frameImg) drawFrame(frameImg, getFocalPointForFrame(idx));
    }, [drawFrame, frames]);

    useEffect(() => {
      resizeCanvas();
      window.addEventListener("resize", resizeCanvas);
      return () => window.removeEventListener("resize", resizeCanvas);
    }, [resizeCanvas]);

    // Stop idle loop
    const stopIdleLoop = useCallback(() => {
      if (idleLoopRef.current !== null) {
        cancelAnimationFrame(idleLoopRef.current);
        idleLoopRef.current = null;
      }
    }, []);

    // Play a section's frames as a video clip at 24fps
    const playSection = useCallback(
      (sectionIndex: number, reverse: boolean = false): Promise<void> => {
        return new Promise((resolve) => {
          if (sectionIndex < 0 || sectionIndex >= SECTIONS.length) { resolve(); return; }
          if (isPlayingRef.current || isFlashingRef.current) { resolve(); return; }

          stopIdleLoop();
          isPlayingRef.current = true;
          setShowScrollHint(false);
          // Dissolve any section quote when scrolling away
          if (sectionQuoteRef.current !== null && !reverse) {
            quoteDisolvingRef.current = true;
            setQuoteDissolving(true);
            // Clear inline styles so CSS animation takes over
            if (quoteInnerElRef.current) {
              quoteInnerElRef.current.style.opacity = '';
              quoteInnerElRef.current.style.transform = '';
            }
            setTimeout(() => {
              setSectionQuote(null);
              sectionQuoteRef.current = null;
              quoteDisolvingRef.current = false;
              setQuoteDissolving(false);
            }, 1500);
          }
          // Dissolve captions when scrolling forward away from section 0
          if (showHadithRef.current && sectionIndex > 0 && !reverse) {
            setHadithDissolving(true);
            setTimeout(() => {
              setShowHadith(false);
              showHadithRef.current = false;
              setHadithDissolving(false);
              setCaptionLines(0);
            }, 1500);
          }
          // When reversing section 0, ensure captions are visible and not dissolving
          // The frame-driven logic will handle showing/hiding them at the right frames
          if (sectionIndex === 0 && reverse) {
            setHadithDissolving(false);
            setShowHadith(true);
            showHadithRef.current = true;
            setCaptionLines(3); // Start fully visible, frame logic will reduce as we reverse
          }
          const section = SECTIONS[sectionIndex];
          const startFrame = section.startFrame - 1; // 0-indexed
          const endFrame = section.endFrame - 1; // 0-indexed

          let frameIdx = reverse ? endFrame : startFrame;
          const FPS_INTERVAL = 1000 / TARGET_FPS;
          let lastTime = performance.now();

          // Preload frames for this section
          for (let i = startFrame; i <= endFrame; i++) {
            updateCurrentFrame(i);
          }

          const playNext = (now: number) => {
            const done = reverse ? frameIdx < startFrame : frameIdx > endFrame;
            if (done) {
              isPlayingRef.current = false;

              if (reverse && sectionIndex > 0) {
                // Land on the previous section's last frame (HD still)
                const prevSection = sectionIndex - 1;
                const prevEndFrame = SECTIONS[prevSection].endFrame - 1; // 0-indexed
                currentFrameRef.current = prevEndFrame;
                drawFrameAtIndex(prevEndFrame);
                currentSectionRef.current = prevSection;
                setCurrentSection(prevSection);
                atSectionStartRef.current = false; // at END of previous section
                // Restore that section's quote
                if (prevSection > 0) {
                  setSectionQuote(prevSection);
                  sectionQuoteRef.current = prevSection;
                  setQuoteDissolving(false);
                } else if (prevSection === 0) {
                  // Section 0 uses the caption system
                  setShowHadith(true); showHadithRef.current = true;
                  setCaptionLines(3);
                  setHadithDissolving(false);
                }
              } else {
                currentSectionRef.current = sectionIndex;
                setCurrentSection(sectionIndex);
                atSectionStartRef.current = reverse; // reverse section 0 = at start
              }

              const progress = reverse
                ? (reverse && sectionIndex > 0
                    ? SECTIONS[sectionIndex - 1].endFrame / TOTAL_FRAMES
                    : (section.startFrame - 1) / TOTAL_FRAMES)
                : section.endFrame / TOTAL_FRAMES;
              onProgressChange?.(progress);

              // Section 0 completion — depends on direction
              if (sectionIndex === 0) {
                if (reverse) {
                  // Scrolled back to beginning — show ummah logo at frame 0
                  setIntroPhase("ummah");
                  introOpacityRef.current = 0;
                  if (introOverlayElRef.current) introOverlayElRef.current.style.opacity = '0';
                  setShowHadith(false); showHadithRef.current = false;
                  setCaptionLines(0);
                } else {
                  // Played forward to end — captions fully visible
                  setIntroPhase("done");
                  introOpacityRef.current = 0;
                  if (introOverlayElRef.current) introOverlayElRef.current.style.opacity = '0';
                  setShowHadith(true); showHadithRef.current = true;
                  setCaptionLines(3);
                }
              }

              // Show scroll hint and section quote unless at very start
              if (!(sectionIndex === 0 && reverse)) {
                setShowScrollHint(true);
                // Show quote for sections that have one (not section 0 — it uses captions)
                if (!reverse && sectionIndex > 0) {
                  setSectionQuote(sectionIndex);
                  sectionQuoteRef.current = sectionIndex;
                  setQuoteDissolving(false);
                }
              }

              resolve();
              return;
            }

            const elapsed = now - lastTime;
            if (elapsed >= FPS_INTERVAL) {
              // Gate: skip advance if target frame isn't decoded yet
              if (!frames.current[frameIdx]) {
                requestAnimationFrame(playNext);
                return;
              }
              lastTime = now - (elapsed % FPS_INTERVAL);
              currentFrameRef.current = frameIdx;
              drawFrameAtIndex(frameIdx);

              // Drive intro overlays during section 0 (clip 1+2)
              // Works identically forward and reverse — frame position determines state
              if (sectionIndex === 0) {
                const f = frameIdx; // 0-indexed frame

                // Logos
                // Compute intro opacity and phase — update ref + DOM directly
                let nextOpacity = 0;
                let nextPhase: "ummah" | "salik" | "done" = "done";
                if (f < 10) {
                  nextPhase = "ummah"; nextOpacity = f / 10;
                } else if (f < 50) {
                  nextPhase = "ummah"; nextOpacity = 1;
                } else if (f < 65) {
                  nextPhase = "ummah"; nextOpacity = 1 - (f - 50) / 15;
                } else if (f < 75) {
                  nextPhase = "salik"; nextOpacity = (f - 65) / 10;
                } else if (f < 130) {
                  nextPhase = "salik"; nextOpacity = 1;
                } else if (f < 145) {
                  nextPhase = "salik"; nextOpacity = 1 - (f - 130) / 15;
                }
                setIntroPhase(nextPhase);
                introOpacityRef.current = nextOpacity;
                if (introOverlayElRef.current) introOverlayElRef.current.style.opacity = String(nextOpacity);

                // Caption lines — frame position determines how many are visible
                if (f < 165) {
                  setCaptionLines(0);
                  setShowHadith(false); showHadithRef.current = false;
                } else if (f < 190) {
                  setCaptionLines(1);
                  setShowHadith(true); showHadithRef.current = true;
                  setHadithDissolving(false);
                } else if (f < 215) {
                  setCaptionLines(2);
                  setShowHadith(true); showHadithRef.current = true;
                  setHadithDissolving(false);
                } else {
                  setCaptionLines(3);
                  setShowHadith(true); showHadithRef.current = true;
                  setHadithDissolving(false);
                }
              }

              // Drive section quote fade via ref + direct DOM (no React re-render per frame)
              // Each section: compute fade progress, update ref, update DOM element
              const updateQuoteFade = (val: number, translateDist: number) => {
                baalFadeRef.current = val;
                if (quoteInnerElRef.current && !quoteDisolvingRef.current) {
                  quoteInnerElRef.current.style.opacity = String(val);
                  quoteInnerElRef.current.style.transform = `translateY(${(1 - val) * translateDist}px)`;
                }
              };

              if (sectionIndex === 1) {
                const rel = frameIdx - 241;
                if (rel < 136) {
                  baalFadeRef.current = 0;
                  if (sectionQuoteRef.current !== null) {
                    setSectionQuote(null); sectionQuoteRef.current = null;
                  }
                } else {
                  if (sectionQuoteRef.current !== 1) {
                    setSectionQuote(1); sectionQuoteRef.current = 1; setQuoteDissolving(false);
                  }
                  updateQuoteFade(Math.min(1, (rel - 136) / 15), 15);
                }
              } else if (sectionIndex === 2) {
                const rel = frameIdx - 392;
                if (rel < 136) {
                  if (sectionQuoteRef.current !== null) {
                    setSectionQuote(null); sectionQuoteRef.current = null;
                  }
                } else {
                  if (sectionQuoteRef.current !== 2) {
                    setSectionQuote(2); sectionQuoteRef.current = 2; setQuoteDissolving(false);
                  }
                  updateQuoteFade(Math.min(1, (rel - 136) / 15), 20);
                }
              } else if (sectionIndex === 3) {
                const rel = frameIdx - 543;
                if (rel < 101) {
                  if (sectionQuoteRef.current !== null) {
                    setSectionQuote(null); sectionQuoteRef.current = null;
                  }
                } else {
                  if (sectionQuoteRef.current !== 3) {
                    setSectionQuote(3); sectionQuoteRef.current = 3; setQuoteDissolving(false);
                  }
                  updateQuoteFade(Math.min(1, (rel - 101) / 15), 20);
                }
              } else if (sectionIndex === 4) {
                const rel = frameIdx - 664;
                if (rel < 101) {
                  if (sectionQuoteRef.current !== null) {
                    setSectionQuote(null); sectionQuoteRef.current = null;
                  }
                } else {
                  if (sectionQuoteRef.current !== 4) {
                    setSectionQuote(4); sectionQuoteRef.current = 4; setQuoteDissolving(false);
                  }
                  updateQuoteFade(Math.min(1, (rel - 101) / 15), 20);
                }
              } else if (sectionQuoteRef.current !== null) {
                setSectionQuote(null);
                sectionQuoteRef.current = null;
                setQuoteDissolving(false);
              }

              const progress = frameIdx / TOTAL_FRAMES;
              onProgressChange?.(progress);

              if (reverse) {
                frameIdx--;
              } else {
                frameIdx++;
              }
            }
            requestAnimationFrame(playNext);
          };
          requestAnimationFrame(playNext);
        });
      },
      [drawFrameAtIndex, updateCurrentFrame, onProgressChange, stopIdleLoop]
    );

    // Play multiple sections back-to-back
    const playSections = useCallback(
      async (startIdx: number, endIdx: number) => {
        for (let i = startIdx; i <= endIdx; i++) {
          await playSection(i);
        }
      },
      [playSection]
    );

    // Handle scroll/wheel/touch to trigger next or previous clip
    useEffect(() => {
      if (!isInitialLoadComplete) return;

      const handleWheel = (e: WheelEvent) => {
        e.preventDefault();
        if (isPlayingRef.current || isFlashingRef.current || scrollCooldownRef.current) return;
        const delta = Math.abs(e.deltaY) > Math.abs(e.deltaX) ? e.deltaY : e.deltaX;

        if (delta > 10) {
          // Forward: if at start of section, play it forward. If at end, play next.
          const cur = currentSectionRef.current;
          const target = atSectionStartRef.current ? cur : cur + 1;
          if (target < SECTIONS.length) {
            scrollCooldownRef.current = true;
            playSection(target);
            setTimeout(() => { scrollCooldownRef.current = false; }, 300);
          }
        } else if (delta < -10) {
          // Backward: if at end of section, reverse it. If at start, reverse previous.
          const cur = currentSectionRef.current;
          const target = atSectionStartRef.current ? cur - 1 : cur;
          if (target >= 0) {
            scrollCooldownRef.current = true;
            playSection(target, true);
            setTimeout(() => { scrollCooldownRef.current = false; }, 300);
          }
        }
      };

      // Touch support for mobile
      let touchStartX = 0;
      let touchStartY = 0;

      const handleTouchStart = (e: TouchEvent) => {
        touchStartX = e.touches[0].clientX;
        touchStartY = e.touches[0].clientY;
      };

      const handleTouchEnd = (e: TouchEvent) => {
        if (isPlayingRef.current || isFlashingRef.current || scrollCooldownRef.current) return;
        const touchEndX = e.changedTouches[0].clientX;
        const touchEndY = e.changedTouches[0].clientY;
        const diffX = touchStartX - touchEndX;
        const diffY = touchStartY - touchEndY;

        if (Math.abs(diffY) > 50 && Math.abs(diffY) > Math.abs(diffX)) {
          if (diffY > 0) {
            const cur = currentSectionRef.current;
            const target = atSectionStartRef.current ? cur : cur + 1;
            if (target < SECTIONS.length) {
              scrollCooldownRef.current = true;
              playSection(target);
              setTimeout(() => { scrollCooldownRef.current = false; }, 300);
            }
          } else {
            const cur = currentSectionRef.current;
            const target = atSectionStartRef.current ? cur - 1 : cur;
            if (target >= 0) {
              scrollCooldownRef.current = true;
              playSection(target, true);
              setTimeout(() => { scrollCooldownRef.current = false; }, 300);
            }
          }
        }
      };

      // Arrow key support
      const handleKeydown = (e: KeyboardEvent) => {
        if (isPlayingRef.current || isFlashingRef.current) return;

        if (e.key === "ArrowRight" || e.key === "ArrowDown") {
          const cur = currentSectionRef.current;
          const target = atSectionStartRef.current ? cur : cur + 1;
          if (target < SECTIONS.length) playSection(target);
        } else if (e.key === "ArrowLeft" || e.key === "ArrowUp") {
          const cur = currentSectionRef.current;
          const target = atSectionStartRef.current ? cur - 1 : cur;
          if (target >= 0) playSection(target, true);
        }
      };

      // Lock page scroll
      document.body.style.overflow = "hidden";

      window.addEventListener("wheel", handleWheel, { passive: false });
      window.addEventListener("touchstart", handleTouchStart, { passive: true });
      window.addEventListener("touchend", handleTouchEnd, { passive: true });
      window.addEventListener("keydown", handleKeydown);

      return () => {
        window.removeEventListener("wheel", handleWheel);
        window.removeEventListener("touchstart", handleTouchStart);
        window.removeEventListener("touchend", handleTouchEnd);
        window.removeEventListener("keydown", handleKeydown);
        document.body.style.overflow = "";
      };
    }, [isInitialLoadComplete, playSection]);

    // Auto-play first section on load
    useEffect(() => {
      if (isInitialLoadComplete) {
        drawFrameAtIndex(0);
        setTimeout(() => {
          playSection(0);
        }, 500);
      }
    }, [isInitialLoadComplete, drawFrameAtIndex, playSection]);

    // Flash sequence (kept for API compatibility)
    useImperativeHandle(ref, () => ({
      playFlashSequence: () =>
        new Promise<void>((resolve) => {
          stopIdleLoop();
          isFlashingRef.current = true;

          const hasFlashFrames = flashFrames.current.some((f) => f !== null);

          if (!hasFlashFrames) {
            const canvas = canvasRef.current;
            if (canvas) {
              if (!ctxRef.current) ctxRef.current = canvas.getContext("2d");
              const ctx = ctxRef.current;
              if (ctx) {
                ctx.fillStyle = "#ffffff";
                ctx.fillRect(0, 0, canvas.width, canvas.height);
              }
            }
            resolve();
            return;
          }

          let frame = 0;
          const FPS_INTERVAL = 1000 / TARGET_FPS;
          let lastTime = performance.now();

          const playNext = (now: number) => {
            if (frame >= FLASH_FRAME_COUNT) {
              resolve();
              return;
            }

            const elapsed = now - lastTime;
            if (elapsed >= FPS_INTERVAL) {
              lastTime = now - (elapsed % FPS_INTERVAL);
              const img = flashFrames.current[frame];
              if (img) {
                drawFrame(img);
              }
              frame++;
            }
            requestAnimationFrame(playNext);
          };
          requestAnimationFrame(playNext);
        }),
    }));

    if (!isInitialLoadComplete) {
      return (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black">
          <div className="text-center text-white">
            <img
              src="/salik-foundation-logo.png"
              alt="Salik Foundation"
              className="mx-auto mb-6 h-12 opacity-60"
            />
            <div className="mb-4 text-sm tracking-[0.2em] uppercase text-white/50">
              Loading experience...
            </div>
            <div className="mx-auto h-1 w-48 overflow-hidden rounded-full bg-white/20">
              <div
                className="h-full rounded-full bg-[#4AB3E2] transition-all duration-300"
                style={{ width: `${Math.round((frames.current.filter(Boolean).length / INITIAL_BATCH_SIZE) * 100)}%` }}
              />
            </div>
          </div>
        </div>
      );
    }

    return (
      <div className="fixed inset-0">
        <canvas
          ref={(el) => {
            (canvasRef as React.MutableRefObject<HTMLCanvasElement | null>).current = el;
            ctxRef.current = null; // reset cached context when canvas element changes
            if (el) resizeCanvas();
          }}
          className="fixed left-0 top-0 w-screen h-screen"
          style={{ zIndex: 2 }}
        />

        {/* Cinematic intro overlays */}
        {introPhase !== "none" && introPhase !== "done" && (
          <IntroOverlay
            ref={introOverlayElRef}
            phase={introPhase}
            initialOpacity={introOpacityRef.current}
          />
        )}

        {/* Section 0 — "500 YEARS OF DARKNESS" headline + subtitle */}
        {showHadith && (
          <Section0Caption dissolving={hadithDissolving} captionLines={captionLines} />
        )}

        {/* Section quotes — positioned per scene */}
        {sectionQuote !== null && (
          <SectionQuotes
            ref={quoteInnerElRef}
            sectionIndex={sectionQuote}
            dissolving={quoteDissolving}
            initialFade={baalFadeRef.current}
          />
        )}

        {/* Cutscene scroll prompt */}
        <ScrollHint visible={showScrollHint} />

        <style>{`
          @keyframes cutsceneFloat {
            0%, 100% { transform: translateY(0); }
            50% { transform: translateY(-5px); }
          }
          @keyframes chevronCascade {
            0% { opacity: 0.1; transform: translateY(-4px); }
            40% { opacity: 1; transform: translateY(0); }
            70% { opacity: 0.5; transform: translateY(4px); }
            100% { opacity: 0.1; transform: translateY(6px); }
          }
          @keyframes textGlow {
            0%, 100% { opacity: 0.85; }
            50% { opacity: 1; }
          }
          @keyframes lineGlow {
            0%, 100% { opacity: 0.6; }
            50% { opacity: 1; }
          }
          @keyframes captionDissolveOut {
            0% {
              opacity: 1;
              transform: translateY(0);
              filter: blur(0px);
            }
            100% {
              opacity: 0;
              transform: translateY(-30px);
              filter: blur(4px);
            }
          }
          @keyframes quoteFadeIn {
            0% { opacity: 0; transform: translateY(15px); }
            100% { opacity: 1; transform: translateY(0); }
          }
          .quote-fade-in {
            animation: quoteFadeIn 1.5s ease-out forwards;
          }
          .caption-dissolve p:nth-child(1) {
            animation: captionDissolveOut 1.2s ease-in forwards;
          }
          .caption-dissolve p:nth-child(2) {
            animation: captionDissolveOut 1.2s ease-in 0.15s forwards;
          }
          .caption-dissolve p:nth-child(3) {
            animation: captionDissolveOut 1.2s ease-in 0.3s forwards;
          }
        `}</style>
      </div>
    );
  }
);

export default ScrollCanvas;
